### ISSUE TITLE
Search MPAA rating

### ISSUE THREAD

**Issue by smidley** [jasongdove/ErsatzTV#215]
I would love to be able to search for movies with a certain MPAA rating.  I would use this to build out a kids movies channel.  It would also be great to have the ability to give that search term a "starting release date".  For example, list all movies that are rated "G" and came out after 1990.

**Comment by jasongdove** [comment]
Thanks for the suggestion. I'll certainly look at synchronizing content rating.

For date searches though, you can use something similar to [this example](https://ersatztv.org/user-guide/search/#1970s-1980s-comedies) like `release_date:199* OR release_date:20*`. It's not particularly intuitive to do range searches like that since all of the search fields are strings, but it works.

**Comment by jasongdove** [comment]
This was added with #218 and will be available in the next release.

**Comment by jasongdove** [comment]
This is now available with [v0.0.40-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.40-prealpha)
