### ISSUE TITLE
proper sorting

### ISSUE THREAD

**Issue by Artiume** [jasongdove/ErsatzTV#290]
love the work you're doing so far, being able to make custom channels is a game changer.

sorting is a little funky, on the collections page, it sorts it alphabetically, but it does it capitalized, a - z then lowercase a - z.

while adding content to a collection, the drop down menu sorts the available collections by their creation date instead alphabetically.

on the schedules page, it doesn't properly sort numerically, it does 1, 10, 2, 20, etc.

out of scope, but on the schedules page and playouts page, could the add new * button be moved to the top, that way you don't have to scroll down to the bottom to create a new instance.

thanks again for all the hard work!

**Comment by jasongdove** [comment]
Thanks for the feedback. In addition to pointing out unexpected behavior, it would help if you could define what expected behavior would be (or what you consider "proper sorting").

For the collections page, I think the implication is that you would want case-insensitive sorting for collection names?

For the collection drop downs, it sounds like you want alphabetical? Also case-insensitive?

For the schedules page, are you referring to the schedule name (a string)?

**Comment by Artiume** [comment]
Yeah. So for collections, they ought to be case insensitive.

![Screenshot_20210624-105954_Firefox](https://user-images.githubusercontent.com/20715731/123285887-71606080-d4db-11eb-9f4a-a428f83fa0c9.jpg)

When adding to a collection from a library, sort them alphabetically as well.

![Screenshot_20210624-105906_Firefox](https://user-images.githubusercontent.com/20715731/123286016-89d07b00-d4db-11eb-938f-d29e98eff47b.jpg)

Here's the schedules page, i give their name the channel number at the beginning i associate it with so that they're roughly in the same order.

![20210624_105836](https://user-images.githubusercontent.com/20715731/123286121-a2d92c00-d4db-11eb-823f-778974827c33.jpg)
