### ISSUE TITLE
Feature: Option to schedule shows in collection in chronological order

### ISSUE THREAD

**Issue by krutburken** [jasongdove/ErsatzTV#369]
If I have a collection of shows, I can't seem to find an option to schedule the episodes of these shows in chronological order. The option does exist if you schedule a specific show, but not if you try to schedule a collection of shows.

I'm looking for something like "Shuffle Chronologically", where the episodes in shows are in chronological order, but the show order is shuffled. As an addition you could also add the "Multiple" playout mode here, to be able to play x number of episodes of each show in chronological order.

**Comment by jasongdove** [comment]
So I think for the most part this is a documentation gap. `Shuffle In Order` should do exactly what you describe (shuffling the order of shows while keeping each show in chronological order).

I'll give the `Multiple` idea some thought.

**Comment by krutburken** [comment]
Thanks for the quick response!

Hm, I did try that, and I now realize when looking closer that it is actually in chronological order, it's just that the shows have different starting points (some begin at s01, some at s07, other at s04 etc). Is there any way to reset the progression here, so they all begin at s01 when creating the schedule?

**Comment by jasongdove** [comment]
The shows all start with their earliest episode (chronologically). I suspect there are a few reasons why that may not appear to be the case late in the day.

1. Playouts always start building at midnight of the current day. So if you build a playout at 22:00 that means there are 22 hours of playout that get scheduled and then immediately trimmed for being in the past. This is kind of a holdover from a very early architectural decision, and I do have a backlog item to revisit whether this is still necessary.
2. Shuffling can cause shows to schedule at different rates because when a collection is shuffled, all items must be played once before any items are repeated. What this means for `Shuffle In Order` is that shows are "balanced" throughout the playout, kind of similar to how music playlists are shuffled. So if you have show A with 10 episodes and show B with 2, you might see A A A B A A B A A A.
3. Shuffling between shows is mostly random (meaning the playout does NOT advance as you described "multiple" above). If you have show A with 5 episodes and show B with 5 episodes, you may see something like AAABABBABBB.  This is another reason shows schedule at different rates.

I *think* what you are seeing is shows scheduling at different rates over a long period of time (building a playout late in the day). If this doesn't sound like what's happening, I'm happy to take a closer look.

**Comment by jasongdove** [comment]
Good catch, that behavior was an accidental carry over from another algorithm that didn't use ordering.

The behavior was corrected with #370 and `Shuffle In Order` will now start all collections/shows from the earliest episode as expected.

**Comment by jasongdove** [comment]
This fix is also in the latest release [v0.0.58-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.58-alpha).

**Comment by krutburken** [comment]
Oh wow, that was fast. Works as expected now, thanks for the fix!
