### ISSUE TITLE
Jellyfin Media Sources using shared network folder instead of folder

### ISSUE THREAD

**Issue by devenator** [jasongdove/ErsatzTV#535]
Hi,

my jellyfin-libraries are all using a unc-shared network folder in addition to the normal path, ie:

Movie Library
-----------------
Folder: /video/Movies
Shared network folder: \\server\video\Movies

so that Kodi can use the native mode. But ErsatzTV, running on the same (linux) server as jellyfin, seems also to try to use the unc path instead of the Folder-path it could access. I've tried to map this back from \\server\video\Movies to  /video/Movies, but it does not seem to work (maybe because the rest of the path is till in unc format, ie.  /video/Movies/Spiderman\Spiderman.avi)...

is there a reason for this (does a unc-path work, if using ErsatzTV on Whindos?), or is this a bug that could/sould be fixed?

Best Regards!

**Comment by jasongdove** [comment]
I think the issue is that UNC paths are not expected from a non-Windows Jellyfin installation, so the path separators are handled incorrectly as you mentioned.

As far as I can tell, if you have the shared network folder configured in Jellyfin there is no way to determine the local folder via the Jellyfin API.

I will give this some more thought.

**Comment by jasongdove** [comment]
Did some more digging in the Jellyfin API and it looks like the path information is there, so I may be able to remove the need for manual path replacements, but will also need to manually check the paths to determine the separator character since the Jellyfin operating system cannot be used for that in this case.

**Comment by jasongdove** [comment]
As a brief update: I do plan on addressing this, but have it ordered behind a new "trash" feature that I'm actively developing because I anticipate that when I make the required change to fix this issue with Jellyfin, some users will need to fix their path replacements and I don't want their content removed, collections emptied, etc.

**Comment by jasongdove** [comment]
This will be fixed in the next release as ErsatzTV no longer uses network paths for Jellyfin media items.

**Comment by jasongdove** [comment]
This is fixed in release [v0.5.4-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.5.4-beta).
