### ISSUE TITLE
TV-Shows are not starting with S1E01

### ISSUE THREAD

**Issue by swoop124** [jasongdove/ErsatzTV#849]
hello,

i have installed ErsatzTV in a Docker container, and it is working with movies well, except of some lags, but this may be a hardware issue. My problem is, that when i add a Schedule with a TV-Show with multiple Seasons, the playout isn't starting with S1E01 but for example with S2E18.
Created the schedule like this:
![grafik](https://user-images.githubusercontent.com/75502165/173439140-1c79e2d5-1bda-4c04-aa6f-225ea030f030.png)

then the Playout looks like this:
![grafik](https://user-images.githubusercontent.com/75502165/173439354-3d0639f5-0737-4cbf-b91f-bd720855d51f.png)

The order is different from show to show.

What could i adjust to play the show in chronological order?

only when i set a fixed startdate it is in the right order, but a day apart.

thx

**Comment by jasongdove** [comment]
The reason it appears this way is because all playouts actually start at midnight of the current day, rather than the time the playout was first built. So the later in the day you rebuild/reset the playout, the later it will appear along the chronological progression.

I will investigate whether this is needed anymore with https://github.com/jasongdove/ErsatzTV/issues/850 but currently this is working as designed.
